site_name: Logaut Docs
site_url: "https://whitemech.github.io/logaut/" 
repo_name: 'whitemech/logaut'
repo_url: "https://github.com/whitemech/logaut"

nav:
- Home: index.md

plugins:
- search

theme:
  name: material

markdown_extensions:
- codehilite
- pymdownx.arithmatex
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- markdown_include.include:
    base_path: docs

extra_javascript:
- 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
